apiVersion: apps/v1
kind: Deployment
metadata:
  name: consignment-service
  labels:
    app: consignment-service
spec:
  selector:
    matchLabels:
      app: consignment-service
  replicas: 1
  template:
    metadata:
      labels:
        app: consignment-service
    spec:
      containers:
        - name: app
          image: koko120/consignment-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: consignment-service
spec:
  selector:
    app: consignment-service
  type: ClusterIP
  ports:
    - name: http
      port: 8001
      targetPort: 8001
